services:
  app:
    build: ./app  
    container_name: app
    ports:
      - "3001:3001"
    volumes:
      - ./app:/app       
    networks:
      - pgnetwork 

  postgres:
    image: postgres:18.3-alpine
    container_name: postgres
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: database
    volumes: 
      - pgdata:/var/lib/postgresql/18/docker
    ports:
      - "5432:5432"
    networks:
      - pgnetwork
  
  pgadmin:
    image: dpage/pgadmin4:8.4  
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - pgnetwork

volumes:
  pgdata:

networks:
  pgnetwork:
    driver: bridge